version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5435
      - DB_USER=postgres
      - DB_PASSWORD=secretCode@81
      - DB_NAME=pr_database
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretCode@81
      POSTGRES_DB: pr_database
    ports:
      - "5435:5435"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
